# SPDX-License-Identifier: GPL-2.0
subdir-y += vf2-overlay
dtb-$(CONFIG_SOC_STARFIVE_JH7110) += jh7110-starfive-visionfive-2-v1.3b.dtb	\
				jh7110-starfive-visionfive-2-A10.dtb	\
				jh7110-starfive-visionfive-2-A11.dtb	\
				jh7110-starfive-visionfive-2-wm8960.dtb	\
				jh7110-starfive-visionfive-2-sof-wm8960.dtb	\
				jh7110-starfive-visionfive-2-ac108.dtb \ 
				jh7110-milkv-mars.dtb
